### ISSUE TITLE
Slicer by curve

### ISSUE THREAD

**Issue by Kaankrby** [BecauseWeCan/BecauseWeDynamo#6]
Hi,
i am using because we dynamo package and after updating v.1 slicer by plane node dissapeared. 
i try to use Slicer By Curve but it didin't work ( tried with a curve on X, Y , and Z)
İ am not a coder guy but try to understand from the github and i find something like this in the codes from the github.  

``

```
 Solid = solid;
            Thickness = thickness;
            Spacing = spacing;
            Plane plane = Plane.ByOriginNormal(curve.StartPoint, curve.Normal);
            Curve curvePlanar = curve;
            if(!curve.IsPlanar)
            {
                plane = Plane.ByBestFitThroughPoints(curve.ToNurbsCurve().ControlPoints());
                curvePlanar = curve.PullOntoPlane(plane);
            }
            CutPlanesPrimary.AddRange(GenerateCutPlanes(plane));
            CutPlanesSecondary.AddRange(GenerateCutPlanes(curvePlanar, origin));
            InitialGeometry = new List<Autodesk.DesignScript.Geometry.Geometry>(1) { curvePlanar };
        }
```

``
İf i don't misunderstand this part creates paralel planes to the curve, not perpandicular. (tried with dyanmo  line by line.)

**Comment by epsilonite** [comment]
hi, I'm in Europe right now but i will let you know as soon as I reinstate slicer plane by node

**Comment by Kaankrby** [comment]
Thank you for your return.

Waiting for it :D.

2016-07-15 12:42 GMT+03:00 epsilonite notifications@github.com:

> hi, I'm in Europe right now but i will let you know as soon as I reinstate
> slicer plane by node
> 
> Sent from the void (upside-down scare quote)
>

**Comment by epsilonite** [comment]
Slice along curve was never fully implemented, and is on hold. 123D make has better slicing capabilites. however slicer.byplane and slicerbyplanelines have been added, and broken code has been made inaccessible, and what is available should now all work.

**Comment by Kaankrby** [comment]
Thanks for your effort.
will you update the files on the dynamo package manager or should i rebuild it from VS.

**Comment by epsilonite** [comment]
thet latest version is now available on the dynamo package manager
